version: '2.1'

networks:
  cheapestpath: {}

services:
  db:
    container_name: mydb
    image: mysql:5.7
    networks:
      - cheapestpath
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    entrypoint: sh -c 'echo "CREATE DATABASE IF NOT EXISTS cheapestpath; CREATE DATABASE IF NOT EXISTS cheapestpath_test;" > /docker-entrypoint-initdb.d/init.sql; /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  node:
    restart: always
    depends_on:
      - db
    networks:
      - cheapestpath
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/srv/app
    environment:
      NODE_ENV: dev
      DB_DATABASE: cheapestpath
      DB_DATABASE_TEST: cheapestpath_test
      DB_HOST: mydb
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: ''
    ports:
      - '8099:8080'
    command: sh -c "yarn && yarn migrate_up && yarn dev"
