version: '3'

networks:
  cheapestpath: {}

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'cheapestpath'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  node:
    depends_on:
    - db
    networks:
    - cheapestpath
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/srv/app
    environment:
      DB_CONNECTION: local
      DB_DATABASE: cheapestpath
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USERNAME: 'user'
      DB_PASSWORD: 'password'
    ports:
    - '8077:8080'
    command: sh -c "npm install && npm run dev"
